### ISSUE TITLE
Does not launch on Amazon Fire Phone

### ISSUE THREAD

**Issue by Alzarath** [daktak/opengapps_downloader#2]
I simply installed it through F-Droid. Fire OS 4 6.6.1. It animates like it's about to launch, but just returns me to the screen I was at.

Not sure what other information I could provide that would help.

**Comment by daktak** [comment]
Are you able to attach any information from logcat? You can filter on opengappsdownloader.
Also which version was this?

**Comment by daktak** [comment]
Ok, I think its the Architecture and Android auto detect mechanism, I've released #3 0.2.1 to try fix this.
If you're quick enough, try to get to settings and set the Arrch/Android values and reload.

**Comment by Alzarath** [comment]
Sorry, thought I mentioned. I was able to start it by building from 3.0. Was using the F-Droid version. (1.0 and 2.0, neither worked)

**Comment by daktak** [comment]
F-Droid should update soon. A day or so.
